
server:
  port: 7676
  
spring: 
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testDB
    username: sa
    password:   
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true     
    
  eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8770/eureka
   instance:
     hostname:localhost
     
  application:
    name: CART-SERVICE